---
kind: pipeline
name: Release kubers
type: docker

trigger:
  ref:
  - refs/tags/*
steps:
  - name: prepare build
    image: alpine
    commands: 
      - apk update && apk add bash
      - mkdir dist
      - cp ./kubers ./dist
      - cp ./completions/_kubers ./dist

  - name: gitea release
    image: plugins/gitea-release
    settings:
      api_key:  
        from_secret: GITEA_SECRET
      base_url: https://git.badhouseplants.net
      files: dist/*
      checksum: sha512
